### ISSUE TITLE
Список проектов

### ISSUE THREAD

**Issue by murych** [lambdafrela/lambda-help#4]
Здесь будут перечислены проекты, которые мы предлагаем разобрать Вам для реализации и презентации в конце семестра.

В комментариях Вы можете предлагать свои идеи для проектов, объединяться в команды и объявлять о своем непосредственном участии. Данный пост будет обновляться по мере появления проектов и участников.

Если вам захотелось работать над одним из указанных проектов - напишите об этом в комментариях. Если вас наберется несколько таких человек, то обсудите между собой работу в команде и напишите сюда (~~а можно в чат в телеграме~~ сюда) окончательный список вашей команды и проект, над которым вы желаете трудиться, например:

**Образец**
Мы собрали команду для работы над проектом **"Бот смишнявок с 9gag"**. Участвуют: @murych, @Euphe, @it-lambda

И в течение суток мы вас добавим в список ниже

**Важно**: использование Python в проектах **не обязательно**, но приветствуется (все же мы именно этот язык изучаем). По нему мы и совет можем дать, и поддержать немного. Также помните, что если ваш код будет написан на чем-то очень экзотическом, то вашей команде, скорее всего, будет сложнее с ним работать.

---

Краткий обзор проектов:
- [ ] [Автомат для проведения олимпиады](#Olymp)
- [ ] [Коллаборативный редкактор кода](#Collab)
- [ ] [Виртуальный навигатор по МАИ](#Navigator)
- [ ] ["Биржа" ручного распознавания текста](#Text)
- [ ] [Picture Lorem ipsum](#Lorem)
- [ ] [Электронный учебник](#Tutorial)
- [ ] [Каталогизатор избранных проектов](#Stars)
- [ ] [Проверка "Теории шести рукопожатий"](#Friends)

---
## <a name="Olymp"></a> Автомат для проведения олимпиады.

Пока условно назовем её `olympics_engine`.

Пусть есть структура файлов
- задачи
  - задача №1
- решения
- тесты
- результаты
  - задача №1

Допустим есть олимпиадная задача `задача1`. Решение каждого участника в виде `py` файла который читает ввод из `stdin`, пишет вывод в `stdout`, лежит в папке "решения" с именем "имя_участника_задача1". В папке **тесты** лежит файл `тесты_задача1`.  Внутри этого файла например 50 тест кейсов. Файл тестов поочередно запускает каждое решение и последовательно подает решению все 50 тест кейсов через `stdin` пока не кончатся тесты или тест не провалится. Результат тестирования решения программа пишет в текстовый файл `имя_участника_результат_задача1`.

Как с помощью такой штуки провести олимпиаду:
1. Выкладываем условия задачи, участники отправляют ответы нам на почту.
2. Мы собираем решения всех участников в папке "решения".
3. Запускаем движок олимпиад `python olymptics_engine -i <dir>` где `<dir>` - директория с задачами. Движок запускает все тесты на всех решениях.
4. (Необязательно) Движок выставляет оценки решениям в зависимости от количества пройденных тестов. 
5. Смотрим результаты тестирования, выкладываем на всеобщее обозрение.

И вытекающий проект:
- Имея такую технологию можно сделать сайт аля hackerrank, codingbat, codinggame, итд итп, когда участники могут отправить своё решение и моментально получить результаты тестирования.
- Это позволит провести олимпиаду на всю Москву, Россию, Мир, итд.
## <a name="Collab"></a> Коллаборативный редкактор кода

Клон [CollabEdit](http://collabedit.com)

Позволяет создать документ, предоставить к нему доступ по ссылке.
В отличие от [CollabEdit](http://collabedit.com) сайт должен позволять применять несколько режимов кодинга - коллаборативный режим (редактируют все участники) и презентативный (редактирует только создатель или выбранная группа людей).

Потенциально high load проект.
## <a name="Navigator"></a> Виртуальный навигатор по МАИ

Интерактивный сайт-навигатор по территории МАИ.
## <a name="Text"></a> "Биржа" ручного распознавания текста

Идейный аналог копирайтинговой биржи.
Два типа пользователей - клиенты и "распознаватели".
Клиент загружает на сайт бумагу с рукописным текстом. Его берутся распознать два-три человека. Вручную перепечатывают текст, заливают результаты. Проводится автоматическое сравнение результатов и слитие между собой наиболее грамотных (с точки зрения грамматики) предложений, результат отправляется заказчику, исполнителям платятся деньги в зависимости от качества вклада.
## <a name="Lorem"></a> Picture Lorem ipsum

Написать веб приложение для работы с картинками.
Для проекта/сайта неодходимо подготовить толпу картинок определённого размера и формы (например, все квадратные 1024*1024). Исходные картинки разные. Опционально - отбор картинок по заданной тематике (тегам).
## <a name="Tutorial"></a> Электронный учебник

Веб приложение, позволяющее создавать курсы тестов по дисциплинам. 
Преподаватели имеют возможность рекдактировать курсы и смореть успеваемость учеников. 
Ученики имеют личные аккаунты, выдаваемые преподавателями, и проходят тесты. 
В учебнике должна быть реализована возможность создавать шаблон задачи. То есть если задача на решение квадратного уравнения `a*x^2 + b*x + c = n` то все числа и коэффициенты могут меняться в заданных пределах. Таким образом каждый ученик открыв эту задачу получит разное уравнение. Так обеспечивается защита от списывания и улучшение обучения. 
Интерфейс для создания задачек должен быть ИЛИ легко используемым преподавателями ИЛИ легко дорабатываться даже не очень умелым программистом. Суть в том, что преподаватели должны иметь возможность создать новый курс задачек с минимальными усилиями. 

Как это работает:
1. Преподаватель генерирует через сайт ключ для ученика. Ключ генерируется из номера студенческого и ФИО. Далее преподаватель через сайт указывает к каким курсам, дисциплинам или тестам получает доступ ученик. 
2. С помощью ключа ученик создает аккаунт и привязывает его к своей почте 
3. Ученик заходит в сайт и видит список доступных ему тестов. Он может посмотреть теоретические выкладки к тестам или начать проходить тест. 
4. Ученик проходит тест. Тест может быть на время, может быть обычным. Тест может иметь возможность прохождения только один раз, а может быть многоразовым. 
5. Ученик получает оценку. Преподаватель получает доступ к оценке ученика, а так же детализацию его ответов на тест. Преподаватель может оценить конкретно какие задачи не решил ученик и обсудить с ним его ошибки.­­­
## <a name="Stars"></a> Каталогизатор избранных проектов

Веб приложение, с помощью которого можно структурировать избранные репозитории на github, bitbucket, etc путем присваивания тегов (ключевых слов) к каждому из них. Примерное описание работы:
1. подключение аккаунтов git-сервисов через OAuth/OAuth2
2. сохранение списка избранных репозиториев в базу данных
3. ручное присвоение пользователем определенных тегов к репозиториям
   3.1. (опционально) задание алгоритмов, которые автоматически классифицируют репозитории и сами присваивают теги, например, по языкам (Python, C++, etc) и направлениям (web, gui, machine learning)
4. возможность гибкиой сортировки и поиска по тегам
5. для каждого репозитория отображать файл README, приводить ссылки на исходный код
## <a name="Friends"></a> Проверка "Теории шести рукопожатий"

Сервис, показывающий связь между двумя пользователями VK по их id. Фактически, строится связанный граф, узлами которого будут друзья друзей одного пользователя, ведущего ко второму:
![](http://i.imgur.com/mS275ef.png)

**Comment by DocItSage** [comment]
Конец семестра - не самое удачное время для активной работы. 
Тем не менее, есть вопрос. Подразумевается реализация проекта с использованием Python или выбор средств на свое усмотрение?

**Comment by btseytlin** [comment]
@LoOnyBiker выбор средств на усмотрение команды. 
Надо помнить, что если вы выбираете Fortran или Brainfuck (для гиперболы), вы так же обрекаете на это своих товарищей по команде. К тому же если окажется, что ваш куратор не имеет представления о технологиях, на которых вы строите приложение, он не сможет вам эффективно помочь.
Поэтому Python очень желателен, но не строго обязателен.
